running 2 rules from 1 config rules/eqeq-python.yaml_0
Running 2 rules...
rules:
- rules.assert-eqeq-is-ok
- rules.eqeq-is-bad
No .semgrepignore found. Using default .semgrepignore rules. See the docs for the list of default ignores: https://semgrep.dev/docs/cli-usage/#ignoring-files
[WARN] Semgrep Core â€” Syntax error
An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

At line targets/bad/invalid_python.py:1: `
    ` was unexpected

Not sending pseudonymous metrics since metrics are configured to AUTO and server usage is False
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/__main__.py", line 34, in <module>
    sys.exit(main())
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/__main__.py", line 20, in main
    cli()
  File "/home/runner/.local/share/virtualenvs/semgrep-GqZ0EjEI/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.local/share/virtualenvs/semgrep-GqZ0EjEI/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/share/virtualenvs/semgrep-GqZ0EjEI/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/.local/share/virtualenvs/semgrep-GqZ0EjEI/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/share/virtualenvs/semgrep-GqZ0EjEI/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/commands/scan.py", line 812, in scan
    output_handler.output(
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/output.py", line 286, in output
    output = self._build_output()
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/output.py", line 382, in _build_output
    return self.formatter.output(
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/formatter/base.py", line 26, in output
    return self.format(
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/formatter/text.py", line 398, in format
    return "\n".join(itertools.chain(output, timing_output))
  File "/home/runner/work/semgrep/semgrep/semgrep/semgrep/formatter/text.py", line 166, in _build_summary
    rule_parsing_time = time_data["rule_parse_info"]
KeyError: 'rule_parse_info'
